version: '3'

volumes:
  TastyLink_pg_data:
  TastyLink_static:
  TastyLink_media:

services:
  db:
    image: postgres:13.10
    container_name: TastyLink_db
    env_file: .env
    volumes:
      - TastyLink_pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/foodgram/
    container_name: TastyLink_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - TastyLink_static:/backend_static
      - TastyLink_media:/app/media

  frontend:
    env_file: .env
    build: ./frontend/
    container_name: TastyLink_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - TastyLink_static:/static

  gateway:
    build: ./nginx/
    container_name: TastyLink_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - TastyLink_static:/static
      - TastyLink_media:/media
