name: Tests WorkFlow

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.10

        env: 
          POSTGRES_USER: django
          POSTGRES_PASSWORD: password
          POSTGRES_DB: foodgram_db

        ports: 
          - 5432:5432

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip 
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/foodgram/requirements.txt 

      - name: Test with flake8 and django tests
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: password
          POSTGRES_DB: foodgram_db
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        
        run: |
          python -m flake8 backend/foodgram
          cd backend/foodgram
          python manage.py test

  send_message:
    runs-on: ubuntu-latest

    needs: tests

    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Тесты прошли успешно!